# Generated by Django 4.2.20 on 2025-03-14 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'книга', 'verbose_name_plural': 'книги'},
        ),
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.CharField(max_length=100, null=True, verbose_name='введите автора'),
        ),
        migrations.AlterField(
            model_name='books',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='введите дату выхода'),
        ),
        migrations.AlterField(
            model_name='books',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='введите описание'),
        ),
        migrations.AlterField(
            model_name='books',
            name='genre',
            field=models.CharField(choices=[('Проза', 'Проза'), ('Приключения', 'Приключения'), ('Роман', 'Роман'), ('Детектив', 'Детектив')], max_length=30, null=True, verbose_name='введите жанр'),
        ),
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(null=True, upload_to='books/', verbose_name='загрузите фото'),
        ),
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='введите цену'),
        ),
        migrations.AlterField(
            model_name='books',
            name='time',
            field=models.TimeField(null=True, verbose_name='введите время'),
        ),
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='введите название'),
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='введите дату выхода')),
                ('description', models.TextField(blank=True, null=True, verbose_name='введите описание')),
                ('grade', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=10, null=True, verbose_name='введите оценку')),
                ('choice_book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='books.books', verbose_name='выберите книгу')),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'отзывы',
            },
        ),
    ]
